### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "fullName": "Ofek Test",
  "username": "ofektest1",
  "email": "ofek1@test.com",
  "password": "123456"
}

###

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "ofek@test.com",
  "password": "123456"
}

###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWNiOWQ4OWNmMWQ3YTcwYjU0NmQ1YzMiLCJpYXQiOjE3NzQ5NTUwNTQsImV4cCI6MTc3NTU1OTg1NH0.iHZ_YTyJp44-oBITIaqvS5v-NifcgqU0iO3UWQHJFRE
@tournamentId = 69cba9bed8fdd4f285036b1e
@matchId = 69cbaa52d8fdd4f285036b2f
@winnerId = 69cba53d66c848a75a5ba46f



### Get Me
GET http://localhost:3000/api/auth/me
Authorization: Bearer {{token}}

###

### Create Tournament
POST http://localhost:3000/api/tournaments
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "ArenaX Test Tournament",
  "gameTitle": "FIFA",
  "format": "single_elimination",
  "maxParticipants": 8,
  "startDate": "2026-04-10T18:00:00.000Z"
}

###

### Get All Tournaments
GET http://localhost:3000/api/tournaments

###

### Join Tournament
POST http://localhost:3000/api/tournaments/{{tournamentId}}/join
Authorization: Bearer {{token}}

###

### Update Tournament (creator only)
PUT http://localhost:3000/api/tournaments/{{tournamentId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Updated Tournament",
  "prizePool": 999
}

###

### Delete Tournament
DELETE http://localhost:3000/api/tournaments/{{tournamentId}}
Authorization: Bearer {{token}}

### Open Tournament
PATCH http://localhost:3000/api/tournaments/{{tournamentId}}/open
Authorization: Bearer {{token}}

###

### Start Tournament
PATCH http://localhost:3000/api/tournaments/{{tournamentId}}/start
Authorization: Bearer {{token}}

###

### Get Tournament Matches
GET http://localhost:3000/api/matches/tournament/{{tournamentId}}

### Get Tournament Matches
GET http://localhost:3000/api/matches/tournament/{{tournamentId}}

###

### Report Match Result
PATCH http://localhost:3000/api/matches/{{matchId}}/result
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "winnerId": "{{winnerId}}",
  "score": "2-0",
  "metadata": {
    "reportedBy": "tournament_creator"
  }
}